name: CI/CD - Epibuilder Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositories
        uses: actions/checkout@v3

      - name: Clone epibuilder sources
        run: |
          mkdir -p sources
          cd sources
          git clone https://github.com/bioinformatics-ufsc/epibuilder-core.git
          git clone https://github.com/bioinformatics-ufsc/epibuilder-backend.git
          git clone https://github.com/bioinformatics-ufsc/epibuilder-frontend.git

      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 21

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Build epibuilder-core
      - name: Build epibuilder-core
        run: |
          cd sources/epibuilder-core
          ./mvnw clean package -DskipTests

      # Build backend (Spring Boot)
      - name: Build backend
        run: |
          cd sources/epibuilder-backend
          ./mvnw clean package -DskipTests
          mkdir -p ../../backend
          cp target/*.jar ../../backend/epibuilder-backend.jar

      # Build frontend (Angular)
      - name: Build frontend
        run: |
          cd sources/epibuilder-frontend
          npm install
          npm run build
          mkdir -p ../../frontend/dist/epibuilder-frontend
          cp -r dist/epibuilder-frontend/* ../../frontend/dist/epibuilder-frontend/

      # Build Debian-based Docker image (CPU)
      - name: Build Docker image (Debian - CPU)
        run: |
          docker build -f Dockerfile.debian -t ${{ secrets.DOCKER_USERNAME }}/epibuilder:debian-cpu .

      # Build Ubuntu-based Docker image (GPU)
      - name: Build Docker image (Ubuntu - GPU)
        run: |
          docker build -f Dockerfile.ubuntu -t ${{ secrets.DOCKER_USERNAME }}/epibuilder:ubuntu-gpu .

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Debian image
      - name: Push Debian image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/epibuilder:debian-cpu

      # Push Ubuntu GPU image
      - name: Push Ubuntu image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/epibuilder:ubuntu-gpu
